create table if not exists BOOKS (
	id  IDENTITY NOT NULL PRIMARY KEY,
	title VARCHAR(100),
	description VARCHAR(500),
	cover_image VARCHAR(1000),
	price NUMERIC,
	author INT
);

insert into BOOKS (id, title, description, cover_image, price, author) values (1, 'I Want to Find You', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/181x100.png/5fa2dd/ffffff', 34,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (2, 'Mr. Destiny', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/198x100.png/5fa2dd/ffffff', 10,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (3, 'Finding Joy', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'http://dummyimage.com/147x100.png/ff4444/ffffff', 77,9);
insert into BOOKS (id, title, description, cover_image, price, author) values (4, 'Very Brady Sequel, A', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/130x100.png/dddddd/000000', 56,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (5, 'Louis C.K.: Live at the Beacon Theater', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/218x100.png/5fa2dd/ffffff', 68,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (6, 'Tarda estate', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 82,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (7, 'Looking for Lenny ', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 15,5);
insert into BOOKS (id, title, description, cover_image, price, author) values (8, 'Sun, The (Solntse)', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff', 57,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (9, 'Great Gatsby, The', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/148x100.png/5fa2dd/ffffff', 36,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (10, 'Timber Falls', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff', 34,5);
insert into BOOKS (id, title, description, cover_image, price, author) values (11, 'Coup de grâce (Der Fangschuß)', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/181x100.png/ff4444/ffffff', 66,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (12, 'Trailer Park of Terror', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/201x100.png/5fa2dd/ffffff', 22,4);
insert into BOOKS (id, title, description, cover_image, price, author) values (13, 'Birder''s Guide to Everything, A', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/177x100.png/cc0000/ffffff', 41,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (14, 'Yossi & Jagger', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/198x100.png/ff4444/ffffff', 56,9);
insert into BOOKS (id, title, description, cover_image, price, author) values (15, 'Internal Affairs', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/136x100.png/dddddd/000000', 89,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (16, 'Kronos (a.k.a. Captain Kronos: Vampire Hunter)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 80,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (17, 'Swinger, The', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 60,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (18, 'Pathfinder', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/220x100.png/cc0000/ffffff', 45,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (19, 'Astronaut Farmer, The', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/235x100.png/cc0000/ffffff', 68,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (20, 'Sky West and Crooked (Gypsy Girl)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/125x100.png/ff4444/ffffff', 56,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (21, 'Red-Headed Woman', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'http://dummyimage.com/231x100.png/dddddd/000000', 32,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (22, 'Venus & Fleur', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/118x100.png/cc0000/ffffff', 46,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (23, 'Ambush Trail', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/227x100.png/cc0000/ffffff', 64,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (24, 'Heli', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'http://dummyimage.com/135x100.png/ff4444/ffffff', 21,4);
insert into BOOKS (id, title, description, cover_image, price, author) values (25, 'Brideshead Revisited', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/131x100.png/dddddd/000000', 83,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (26, 'Knocked Up', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/111x100.png/cc0000/ffffff', 84,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (27, 'A Night at the Movies: The Suspenseful World of Thrillers', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', 21,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (28, 'Dracula: Dead and Loving It', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/116x100.png/ff4444/ffffff', 56,8);
insert into BOOKS (id, title, description, cover_image, price, author) values (29, 'Auntie from Chicago, The (I theia apo to Chicago)', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/116x100.png/ff4444/ffffff', 91,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (30, 'Zodiac', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/237x100.png/ff4444/ffffff', 41,9);
insert into BOOKS (id, title, description, cover_image, price, author) values (31, 'Come Undone (Cosa voglio di più)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/165x100.png/5fa2dd/ffffff', 71,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (32, 'Nothing to Lose (a.k.a. Ten Benny)', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'http://dummyimage.com/184x100.png/cc0000/ffffff', 54,9);
insert into BOOKS (id, title, description, cover_image, price, author) values (33, 'Sisterhood of the Traveling Pants, The', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/182x100.png/5fa2dd/ffffff', 70,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (34, 'I Went Down', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/247x100.png/cc0000/ffffff', 51,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (35, 'Sun on the Horizon', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/238x100.png/dddddd/000000', 70,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (36, 'Sweet November', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://dummyimage.com/233x100.png/ff4444/ffffff', 97,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (37, 'Everybody''s Famous! (Iedereen beroemd!)', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/145x100.png/dddddd/000000', 38,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (38, 'Far from the Madding Crowd', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/158x100.png/cc0000/ffffff', 73,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (39, 'Front Page Woman', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/203x100.png/cc0000/ffffff', 10,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (40, 'Skin Game, The', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/145x100.png/5fa2dd/ffffff', 85,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (41, 'My Wife Is a Gangster (Jopog manura)', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'http://dummyimage.com/122x100.png/ff4444/ffffff', 57,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (42, 'The Wonders', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/199x100.png/dddddd/000000', 11,9);
insert into BOOKS (id, title, description, cover_image, price, author) values (43, 'Sorority Row', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/246x100.png/ff4444/ffffff', 77,5);
insert into BOOKS (id, title, description, cover_image, price, author) values (44, 'Tsotsi', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/195x100.png/cc0000/ffffff', 42,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (45, 'Lawless Breed, The', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/121x100.png/ff4444/ffffff', 50,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (46, 'Claire of the Moon', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/231x100.png/5fa2dd/ffffff', 24,4);
insert into BOOKS (id, title, description, cover_image, price, author) values (47, 'Cake', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 19,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (48, 'T-Men', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/119x100.png/5fa2dd/ffffff', 43,8);
insert into BOOKS (id, title, description, cover_image, price, author) values (49, 'The Missionaries', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/145x100.png/cc0000/ffffff', 36,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (50, 'White Stripes Under Great White Northern Lights, The', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/215x100.png/cc0000/ffffff', 72,8);
insert into BOOKS (id, title, description, cover_image, price, author) values (51, 'Knights of Bloodsteel', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/148x100.png/ff4444/ffffff', 44,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (52, 'Soul Kitchen', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'http://dummyimage.com/248x100.png/cc0000/ffffff', 47,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (53, 'Manufacturing Dissent', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 34,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (54, 'Rails & Ties', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'http://dummyimage.com/134x100.png/ff4444/ffffff', 52,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (55, 'Conserva Acabada', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/238x100.png/dddddd/000000', 79,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (56, 'Flakes', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://dummyimage.com/199x100.png/dddddd/000000', 90,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (57, 'Bulworth', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'http://dummyimage.com/159x100.png/dddddd/000000', 66,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (58, 'Confidence Girl', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/114x100.png/dddddd/000000', 25,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (59, 'Shutter', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/245x100.png/5fa2dd/ffffff', 14,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (60, 'Dead Silence', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/186x100.png/dddddd/000000', 83,5);
insert into BOOKS (id, title, description, cover_image, price, author) values (61, 'Kung Fu Panda: Secrets of the Furious Five', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'http://dummyimage.com/212x100.png/cc0000/ffffff', 45,5);
insert into BOOKS (id, title, description, cover_image, price, author) values (62, 'Hills Have Eyes II, The', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/211x100.png/dddddd/000000', 95,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (63, 'Player, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'http://dummyimage.com/170x100.png/ff4444/ffffff', 46,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (64, 'Voyage to the Bottom of the Sea', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'http://dummyimage.com/232x100.png/dddddd/000000', 50,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (65, 'Blood and Sand', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/184x100.png/5fa2dd/ffffff', 16,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (66, 'Them!', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'http://dummyimage.com/105x100.png/5fa2dd/ffffff', 83,8);
insert into BOOKS (id, title, description, cover_image, price, author) values (67, 'Sum of All Fears, The', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/190x100.png/cc0000/ffffff', 22,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (68, 'Lifted', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 13,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (69, 'Schwestern', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/200x100.png/dddddd/000000', 22,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (70, 'Man on a Ledge', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/148x100.png/dddddd/000000', 75,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (71, 'Lucky Luke: The Ballad of the Daltons', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/151x100.png/dddddd/000000', 91,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (72, 'Edison Force (a.k.a. Edison)', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://dummyimage.com/151x100.png/cc0000/ffffff', 65,8);
insert into BOOKS (id, title, description, cover_image, price, author) values (73, 'Electric House, The', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://dummyimage.com/194x100.png/dddddd/000000', 49,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (74, 'Quills', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'http://dummyimage.com/161x100.png/cc0000/ffffff', 60,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (75, 'Finding North', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/229x100.png/ff4444/ffffff', 70,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (76, 'Bridge to Terabithia', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://dummyimage.com/136x100.png/ff4444/ffffff', 29,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (77, 'Sam Peckinpah: Man of Iron', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/210x100.png/dddddd/000000', 74,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (78, 'Wild Things', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://dummyimage.com/237x100.png/cc0000/ffffff', 24,4);
insert into BOOKS (id, title, description, cover_image, price, author) values (79, 'Not Reconciled (Nicht versöhnt oder Es hilft nur Gewalt wo Gewalt herrscht)', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/238x100.png/ff4444/ffffff', 45,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (80, 'City Slickers', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'http://dummyimage.com/145x100.png/cc0000/ffffff', 84,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (81, 'Defending Your Life', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'http://dummyimage.com/132x100.png/5fa2dd/ffffff', 84,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (82, 'Perfect Man, The', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'http://dummyimage.com/193x100.png/5fa2dd/ffffff', 28,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (83, 'Hue and Cry', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'http://dummyimage.com/179x100.png/cc0000/ffffff', 47,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (84, 'Teenage Mutant Ninja Turtles: Turtles Forever', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 25,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (85, 'Mind Reader, The', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://dummyimage.com/113x100.png/cc0000/ffffff', 13,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (86, 'Find Me Guilty', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 42,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (87, 'Body of Evidence', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/210x100.png/dddddd/000000', 11,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (88, 'Holly', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/163x100.png/cc0000/ffffff', 42,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (89, 'Cry of the City', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'http://dummyimage.com/118x100.png/dddddd/000000', 50,3);
insert into BOOKS (id, title, description, cover_image, price, author) values (90, 'Eden Lake', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://dummyimage.com/230x100.png/cc0000/ffffff', 79,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (91, 'Voyage to Cythera (Taxidi sta Kythira)', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://dummyimage.com/186x100.png/dddddd/000000', 93,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (92, 'Back In Action', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://dummyimage.com/184x100.png/dddddd/000000', 77,6);
insert into BOOKS (id, title, description, cover_image, price, author) values (93, 'Gold Rush, The', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/239x100.png/ff4444/ffffff', 62,7);
insert into BOOKS (id, title, description, cover_image, price, author) values (94, 'Source Family, The', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'http://dummyimage.com/246x100.png/dddddd/000000', 88,4);
insert into BOOKS (id, title, description, cover_image, price, author) values (95, 'Mumford', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://dummyimage.com/147x100.png/cc0000/ffffff', 33,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (96, 'Angel''s Egg (Tenshi no tamago)', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/179x100.png/ff4444/ffffff', 16,2);
insert into BOOKS (id, title, description, cover_image, price, author) values (97, 'High and Dry', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'http://dummyimage.com/113x100.png/dddddd/000000', 14,10);
insert into BOOKS (id, title, description, cover_image, price, author) values (98, 'Minnie and Moskowitz', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/155x100.png/cc0000/ffffff', 22,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (99, 'Paper Birds (Pájaros de papel)', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'http://dummyimage.com/222x100.png/cc0000/ffffff', 61,1);
insert into BOOKS (id, title, description, cover_image, price, author) values (100, 'Yi Yi', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://dummyimage.com/141x100.png/ff4444/ffffff', 38,6);

create table users (
	id IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(50),
	last_name VARCHAR(50),
	pseudonym VARCHAR(50),
	is_banned INT(1),
	username VARCHAR(15),
	password VARCHAR(100)
);
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (1, 'Bar', 'Alger', 'Largeleaf Gypsoplaca Lichen', 0,'Bar01', '{bcrypt}$2a$10$xhfbV.99cLX3GzUPfOLVHOuZwmHPOeEUVNWXNySFDExqe.Mess7BK');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (2, 'Temp', 'Morrad', '''ohe Makai', 1,'Temp01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (3, 'Darth', 'Vader', 'Meadow Knapweed', 1,'Darth01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (4, 'Ware', 'Huckerbe', 'Corkwood Tree', 0,'Ware01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (5, 'Marjorie', 'Antoszewski', 'Sharpleaf Baby''s-breath', 0,'Marjorie01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (6, 'Winny', 'Boyda', 'Pringle''s Tarwort', 0,'Winny01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (7, 'Masha', 'McGlue', 'Maiden Fern', 0,'Masha01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (8, 'Jaymie', 'Dowsey', 'Haussknecht''s Clover', 0,'Jaymie01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (9, 'Kirstin', 'Rathjen', 'Laupahoehoe Phyllostegia', 0,'Kirstin01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');
insert into users (id, name, last_name, pseudonym, is_banned, username, password) values (10, 'Arden', 'Tipens', 'Bryum Moss', 0,'Arden01', '{bcrypt}$2a$10$VrK6S.8kStcW.nUISQeVI.BBENoAVaM10LY3mMaphaBJY9sKfqoo6');